trigger:
    batch: true
    branches:
        include:
        - azure-pl

strategy:
  matrix:
    Linux:
      imageName: 'ubuntu-16.04'
    macOS:
      imageName: 'macos-10.14'
    Windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)
  
steps:
  - checkout: self
    clean: true
    displayName: Checkout ccache sources
  - script: |
      sudo apt install -y elfutils gperf libzstd1-dev libb2-dev
    displayName: Install dependencies
    condition: ne( variables['Agent.OS'], 'Windows_NT' )

  - script: |
      choco install msys2 --params="/InstallDir:%CD:~0,2%\msys64 /NoUpdate /NoPath"
      set PATH=%CD:~0,2%\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
      %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syyuu
      %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syuu
      %CD:~0,2%\msys64\usr\bin\pacman -S --needed --noconfirm msys2-devel
      %CD:~0,2%\msys64\usr\bin\pacman -S --needed --noconfirm zlib zlib-devel
    displayName: Install and update MSYS2 and dependencies
    env: 
      MSYS2_FC_CACHE_SKIP: 1
    condition: eq( variables['Agent.OS'], 'Windows_NT' )

  - script: |
      ./autogen.sh
      ./configure
      make
    displayName: Build ccache
    env:
      MSYSTEM: MSYS
      CHERE_INVOKING: yes